### ISSUE TITLE
Typo in terms of use

### ISSUE THREAD

**Issue by furkanarius** [mysteriumnetwork/terms#11]
In "terms of use" document both for node and VPN, there's this phrase:

> You shall use the Network for any purpose that is unlawful or prohibited by these Terms or any Applicable Law.

It should say it shall **NOT**. I'm unable to edit it, so would be great if you can change it

**Comment by Donatas-MN** [comment]
You should be able to Edit it here: https://github.com/mysteriumnetwork/terms/blob/master/documents/TERMS_END_USER.md - just click pencil icon:
![Pasted_Image_2022-08-02_12_27](https://user-images.githubusercontent.com/91055712/182341669-32f2ffce-ab92-4062-8474-dba22c94c2b7.jpg)
